#!/usr/bin/env python3
"""Insert the 15 blog post ideas from tinka_blog_post_ideas_v2.md into content_ideas.

These were generated by parent task t_61a55ee1 and cover 30 keywords
across 5 categories (local city guides, seasonal, buyer's guides,
niche verticals, geographic versions).

Usage:
    python scripts/ingest_v2_blog_ideas.py
    python scripts/ingest_v2_blog_ideas.py --dry-run
"""
import argparse
import logging
import os
import re
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("v2-blog-ingest")

BASE = Path(__file__).resolve().parent.parent
DB = BASE / "data" / "seo_dashboard.db"
V2_MD = BASE / "data" / "tinka_blog_post_ideas_v2.md"

# The 15 ideas extracted from the markdown, manually structured for accuracy
IDEAS = [
    {
        "title": "Sensory Bubbles for Autism: A Complete Guide for Parents",
        "target_keyword": "Sensory Bubbles for Autism",
        "category": "niche-verticals",
        "estimated_searches": 370,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "parent-guide",
        "market": "AU+NZ",
        "h2_outline": (
            "- Why bubbles work for sensory play\n"
            "- How Tinka's bio-grade formula is safe for sensory seekers\n"
            "- 5 sensory bubble activities for children with autism\n"
            "- Calming vs exciting: when to use slow vs giant bubbles\n"
            "- Setting up a sensory bubble zone at home\n"
            "- Expert tip: pairing bubble play with deep pressure activities\n"
            "- FAQ: Are bubbles safe for children with sensory sensitivities?"
        ),
    },
    {
        "title": "Giant Bubbles vs Bubble Machines: Which Is Best for Your Party?",
        "target_keyword": "Bubble Machine Australia",
        "category": "buyers-guide",
        "estimated_searches": 660,
        "opportunity_score": 7.0,
        "effort": "medium",
        "content_type": "comparison",
        "market": "AU",
        "h2_outline": (
            "- The two approaches: bubble machines vs giant bubbles\n"
            "- Comparison table: cost, effect, maintenance, wow factor\n"
            "- When to choose a bubble machine\n"
            "- When giant bubbles win\n"
            "- Tinka's giant bubble kits vs top bubble machine brands\n"
            "- Hybrid approach: using both for maximum party impact\n"
            "- Verdict by event type"
        ),
    },
    {
        "title": "The Perfect Wedding Bubble Exit: Complete Planning Guide (Australia)",
        "target_keyword": "Wedding Bubble Exit Australia",
        "category": "seasonal",
        "estimated_searches": 530,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "wedding-guide",
        "market": "AU",
        "h2_outline": (
            "- Why bubbles are replacing confetti and rice at Australian weddings\n"
            "- Guest coordination: how to organise 30+ guests for a bubble aisle\n"
            "- Choosing the right wand for your wedding exit\n"
            "- Photo tips: timing, lighting, positioning for perfect shots\n"
            "- DIY bubble favours vs rental kits\n"
            "- Real Australian wedding examples\n"
            "- Printable wedding exit coordination checklist"
        ),
    },
    {
        "title": "The Perfect Wedding Bubble Send Off: Complete Guide (New Zealand)",
        "target_keyword": "Wedding Bubble Send Off NZ",
        "category": "seasonal",
        "estimated_searches": 380,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "wedding-guide",
        "market": "NZ",
        "h2_outline": (
            "- The rise of Kiwi weddings using bubbles\n"
            "- Where in NZ to get married with the best bubble photo conditions\n"
            "- NZ wedding venues that love bubble exits\n"
            "- Wind and weather: how to plan around NZ's conditions\n"
            "- Tinka wedding packs: bulk ordering for NZ weddings\n"
            "- Kiwi real wedding case study\n"
            "- Pricing comparison: bubbles vs alternatives for NZ weddings"
        ),
    },
    {
        "title": "Best Giant Bubble Recipe in Australia: 5 Recipes Tested & Compared",
        "target_keyword": "Best Giant Bubble Recipe Australia",
        "category": "how-to",
        "estimated_searches": 1520,
        "opportunity_score": 8.5,
        "effort": "easy",
        "content_type": "recipe",
        "market": "AU",
        "h2_outline": (
            "- What makes a great giant bubble recipe?\n"
            "- Recipe 1: Classic glycerin method\n"
            "- Recipe 2: Corn syrup method\n"
            "- Recipe 3: Guar gum method (professional-grade)\n"
            "- Recipe 4: Baking powder method (bouncy bubbles)\n"
            "- Recipe 5: Tinka Concentrate method\n"
            "- Side-by-side results table\n"
            "- Verdict: when to DIY and when to use Tinka Concentrate"
        ),
    },
    {
        "title": "Giant Bubbles Wellington: Where to Play, Party & Buy",
        "target_keyword": "Giant Bubbles Wellington",
        "category": "local",
        "estimated_searches": 170,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "city-guide",
        "market": "NZ",
        "h2_outline": (
            "- Best Wellington parks for giant bubbles\n"
            "- Wellington windy conditions: why Tinka's Windy Day Wand is essential\n"
            "- Birthday party bubble setups in Wellington\n"
            "- Wellington bubble entertainers and how to book\n"
            "- Wellington stockists (where to buy Tinka locally)\n"
            "- Wellington school holiday bubble activities\n"
            "- Map of best Wellington bubble spots"
        ),
    },
    {
        "title": "Giant Bubbles Christchurch: Ultimate Family Guide to Bubble Fun",
        "target_keyword": "Giant Bubbles Christchurch",
        "category": "local",
        "estimated_searches": 240,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "city-guide",
        "market": "NZ",
        "h2_outline": (
            "- Christchurch's best open spaces for giant bubbles\n"
            "- After-quake family activities: why bubbles work perfectly\n"
            "- Christchurch birthday party hubs\n"
            "- School holiday bubble activities in Christchurch\n"
            "- Christchurch stockists and delivery options\n"
            "- Indoor bubble alternative for rainy days"
        ),
    },
    {
        "title": "Giant Bubbles Gold Coast: Parks, Beach Parties & Stockists",
        "target_keyword": "Giant Bubbles Gold Coast",
        "category": "local",
        "estimated_searches": 100,
        "opportunity_score": 8.5,
        "effort": "medium",
        "content_type": "city-guide",
        "market": "AU",
        "h2_outline": (
            "- Best Gold Coast parks and beaches for giant bubbles\n"
            "- Hot and humid conditions: how to make the best bubbles\n"
            "- Gold Coast party venues that work with bubble entertainment\n"
            "- School holiday bubble ideas for Gold Coast families\n"
            "- Where to buy Tinka on the Gold Coast\n"
            "- Tourist appeal: bubbles for holiday rentals"
        ),
    },
    {
        "title": "Eco Friendly Bubbles NZ: The Complete Guide to Sustainable Bubble Fun",
        "target_keyword": "Eco Friendly Bubbles NZ",
        "category": "safety",
        "estimated_searches": 430,
        "opportunity_score": 12.0,
        "effort": "medium",
        "content_type": "sustainability-guide",
        "market": "NZ",
        "h2_outline": (
            "- Why standard bubble solutions harm the environment\n"
            "- Tinka's bio-grade formula: what makes it different\n"
            "- Environmental comparison: Tinka vs leading brands\n"
            "- DIY eco-friendly bubble recipe\n"
            "- Sustainable bubble play tips for eco-conscious Kiwi families\n"
            "- Tinka's packaging and carbon footprint initiatives\n"
            "- NZ environmental certifications and what they mean"
        ),
    },
    {
        "title": "Bubble Wand Australia: The Complete Buyer's Guide for 2026",
        "target_keyword": "Bubble Wand Australia",
        "category": "buyers-guide",
        "estimated_searches": 820,
        "opportunity_score": 7.5,
        "effort": "easy",
        "content_type": "buyers-guide",
        "market": "AU",
        "h2_outline": (
            "- The Australian bubble wand market: cheap vs professional\n"
            "- Tinka wand range vs warehouse store wands\n"
            "- Comparison table: price, size, durability, bubble quality\n"
            "- Which wand for which age group\n"
            "- Wand + solution bundles vs buying separately\n"
            "- Care and storage to make your wand last\n"
            "- Australian shipping and delivery for Tinka wands"
        ),
    },
    {
        "title": "Eco-Friendly Kids' Birthday Party Activities: Sustainable Fun Beyond Bubbles",
        "target_keyword": "Eco Friendly Kids Birthday Party Activities",
        "category": "party",
        "estimated_searches": 410,
        "opportunity_score": 8.0,
        "effort": "medium",
        "content_type": "listicle",
        "market": "AU+NZ",
        "h2_outline": (
            "- The rise of eco-friendly kids parties in Australia and NZ\n"
            "- 5 sustainable party activities (giant bubbles are #1)\n"
            "- Non-toxic bubble games for toddlers and babies\n"
            "- Eco-friendly party favours that don't create plastic waste\n"
            "- Sustainable decorations, plates, and wrapping\n"
            "- Party food without single-use plastics\n"
            "- How to throw a zero-waste bubble party with Tinka"
        ),
    },
    {
        "title": "Outdoor Montessori Activities NZ: Using Giant Bubbles for Hands-On Learning",
        "target_keyword": "Outdoor Montessori Activities NZ",
        "category": "educational",
        "estimated_searches": 660,
        "opportunity_score": 8.0,
        "effort": "medium",
        "content_type": "educational-guide",
        "market": "NZ",
        "h2_outline": (
            "- What makes giant bubbles a Montessori-aligned activity\n"
            "- Practical life skills: pouring, mixing, cleaning up\n"
            "- Sensorial exploration: iridescence, wind patterns, bubble physics\n"
            "- Language development: describing colours, shapes, movement\n"
            "- Gross motor skills: chasing, popping, creating bubbles\n"
            "- Printable Montessori bubble activity cards\n"
            "- Setting up a Montessori bubble station outdoors"
        ),
    },
    {
        "title": "Christmas Gift Guide for NZ Kids 2026: Top Toy & Experience Gifts",
        "target_keyword": "Christmas Gift for Kids NZ",
        "category": "seasonal",
        "estimated_searches": 1080,
        "opportunity_score": 6.5,
        "effort": "easy",
        "content_type": "gift-guide",
        "market": "NZ",
        "h2_outline": (
            "- 2026's best Kiwi Christmas gifts for kids: experience over things\n"
            "- Top 10 gift ideas by age\n"
            "- Giant Bubble Kit NZ: the gift that keeps on giving\n"
            "- Experience gifts: bubble workshops, tickets, subscriptions\n"
            "- Budget-friendly bubble gifts under $50\n"
            "- Where to buy in NZ before Christmas cutoff\n"
            "- Printable Christmas gift checklist for parents"
        ),
    },
    {
        "title": "Party Bubbles Australia: The Ultimate Guide to Bubble-Themed Celebrations",
        "target_keyword": "Party Bubbles Australia",
        "category": "party",
        "estimated_searches": 790,
        "opportunity_score": 7.5,
        "effort": "medium",
        "content_type": "party-guide",
        "market": "AU",
        "h2_outline": (
            "- Why bubble-themed parties are trending in Australia\n"
            "- Party bubble station setup (DIY vs Tinka kit)\n"
            "- 10 bubble party activities for Australian kids\n"
            "- Party favours that keep the bubble fun going\n"
            "- Budget by party size (10, 20, 30+ guests)\n"
            "- Outdoor vs indoor considerations for Australian weather\n"
            "- Printable bubble party planning checklist"
        ),
    },
    {
        "title": "Giant Bubbles Hamilton NZ: Family Guide to Events & Outdoor Fun",
        "target_keyword": "Giant Bubbles Hamilton NZ",
        "category": "local",
        "estimated_searches": 100,
        "opportunity_score": 8.0,
        "effort": "medium",
        "content_type": "city-guide",
        "market": "NZ",
        "h2_outline": (
            "- Hamilton Gardens: the most magical bubble spot in the Waikato\n"
            "- Other Hamilton parks for giant bubbles\n"
            "- Hamilton party venues perfect for bubble entertainment\n"
            "- Hamilton's bubble entertainers: options and pricing\n"
            "- Where to buy Tinka Giant Bubbles in Hamilton\n"
            "- School holiday bubble activities in the Waikato\n"
            "- Connecting to broader Waikato regional bubble spots"
        ),
    },
]


def get_conn():
    conn = sqlite3.connect(str(DB))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


def run(dry_run: bool = False):
    log.info("=" * 55)
    log.info(f"V2 BLOG POST IDEA INGESTION{' (DRY RUN)' if dry_run else ''}")
    log.info(f"DB: {DB}")
    log.info(f"Source: {V2_MD}")
    log.info(f"Ideas to process: {len(IDEAS)}")
    log.info("=" * 55)

    conn = get_conn() if not dry_run else None

    new_count = 0
    updated_count = 0
    skipped_count = 0

    for idea in IDEAS:
        if not idea.get("title"):
            skipped_count += 1
            continue

        title = idea["title"]
        target_kw = idea["target_keyword"]
        category = idea["category"]
        est_searches = idea["estimated_searches"]
        opp_score = idea["opportunity_score"]
        effort = idea["effort"]
        content_type = idea["content_type"]
        outline = idea.get("h2_outline", "")
        market = idea.get("market", "AU+NZ")
        source = "parent-task-v2"

        if dry_run:
            log.info(f"  [dry-run] WOULD ADD: {title[:70]} | kw={target_kw[:30]} | opp={opp_score} | vol={est_searches} | market={market}")
            continue

        # Check by title (case-insensitive)
        existing = conn.execute(
            "SELECT id FROM content_ideas WHERE title=? COLLATE NOCASE",
            (title,),
        ).fetchone()

        if existing:
            conn.execute(
                """UPDATE content_ideas SET
                   target_keyword=?, category=?, estimated_searches=?,
                   opportunity_score=?, effort=?, content_type=?, outline=?,
                   source=?, status=?
                   WHERE id=?""",
                (target_kw, category, est_searches, opp_score, effort,
                 content_type, outline, source, "backlog", existing["id"]),
            )
            updated_count += 1
            log.info(f"  UPDATE [{existing['id']}]: {title[:60]}")
        else:
            conn.execute(
                """INSERT INTO content_ideas
                   (title, target_keyword, category, estimated_searches, opportunity_score,
                    effort, content_type, outline, source, status)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (title, target_kw, category, est_searches, opp_score,
                 effort, content_type, outline, source, "backlog"),
            )
            new_count += 1
            log.info(f"  INSERT: {title[:60]}")

    if conn:
        conn.commit()
        total = conn.execute("SELECT COUNT(*) FROM content_ideas").fetchone()[0]
        log.info(f"")
        log.info(f"Results: {new_count} new, {updated_count} updated, {skipped_count} skipped")
        log.info(f"Total content_ideas now: {total}")
        conn.close()

    log.info("=" * 55)


if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Insert v2 blog post ideas")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    run(dry_run=args.dry_run)
